### ISSUE TITLE
Small Improvements

### ISSUE THREAD

**Issue by MehmetUzel** [zeynepalaka/portfolio#1]
-Leaving some fields with Lorem text does not give a great feel about website

-Font ("Herr Von Muellerhoff") that used in some of the fields makes hard to read

-About Me section should be changed
  1. Age is not relevant it can be removed
  2. Gender is not relevant it can be also removed
  3. If you don't know another language rather than the language which you prepared your website its also irrelevant so you can remove Turkish 
  
-Adding bars which shows percentage about your skills are also not helping No one wants to work with someone who said they are 
  %75 percent with UI design. Just list your skills and they will measure your level by their own way.

These are some of the suggestions that will improve your portfolio hope that helps.

**Comment by zeynepalaka** [comment]
Thanks for your suggestions.

Mehmet Uzel ***@***.***>, 29 Haz 2022 Çar, 18:45 tarihinde
şunu yazdı:
